docs: update docs for alert/autocomplete/carousel, etc.
ecomfe/veui-docs pull request #11
Opened 2021-09-17 11:00 UTC by xiaodemen

2021-09-17 11:28 UTC, Justineo requested changes

2021-09-17 11:28 UTC, Justineo commented on one/docs/demo/autocomplete/match.vue
> +      // 不要 group
把自定义的逻辑写完整吧

2021-09-17 11:28 UTC, Justineo commented on one/docs/demo/autocomplete/match.vue
> +  section + section {
selector 前面统一空一行吧

2021-09-17 11:28 UTC, Justineo commented on one/docs/components/alert.md
> +### extra 插槽
这个写文字描述吧

```suggestion
### 额外内容
```

2021-09-17 11:28 UTC, Justineo commented on one/docs/components/autocomplete.md
> +设置 `strict` 属性来指定严格模式，若输入值没有完全匹配建议值，那么会清空输入值。
在失焦时？

2021-09-17 11:28 UTC, Justineo commented on one/docs/demo/autocomplete/match.vue
> +<template>
这个就叫 custom.vue？

2021-09-17 11:28 UTC, Justineo commented on one/docs/components/autocomplete.md
> +设置 `match` 属性来自定义自定义高亮逻辑。
补充描述一下 `filter` 吧

2021-09-17 11:28 UTC, Justineo commented on one/docs/components/autocomplete.md
> +设置 `match` 属性来自定义自定义高亮逻辑。
是不是可以搞一个 tip 详述一下具体差异

2021-09-21 15:48 UTC, Justineo requested changes

2021-09-21 15:48 UTC, Justineo commented on one/docs/components/autocomplete.md
> +`match` 一般是用来实现高亮的逻辑，比如实现模糊搜索等，而 `filter` 是控制是否命中，比如希望搜索结果中都是叶子节点，那么 `filter` 过滤掉父节点即可。
```suggestion
`match` 用于高亮显示匹配文本的逻辑；而 `filter` 是控制是否命中。默认情况下 `filter` 会过滤掉未被 `match` 匹配的节点，且将包含非叶子节点。如希望搜索结果中都是叶子节点，可通过重写 `filter` 过滤掉非叶子节点。
```

2021-09-21 15:48 UTC, Justineo commented on one/docs/components/autocomplete.md
> +| `match` | `(item, keyword, { ancestors }) => boolean | Array<[number, number]>` | - | 支持自定义高亮逻辑， 默认大小写不敏感。 |
```suggestion
| `match` | `(item, keyword, { ancestors }) => boolean | [number, number] | Array<[number, number]>` | - | 支持自定义高亮逻辑，默认进行大小写不敏感的子串匹配。 |
```

其它地方也需要改一下，这里应该稍微详细一点，不然别的地方说参考 Autocomplete 好像也没有意义。

2021-09-21 15:48 UTC, Justineo commented on one/docs/components/number-input.md
> +### 精度位数和递增(减)
```suggestion
### 精度位数和递增/递减
```

2021-09-21 15:48 UTC, Justineo commented on one/docs/components/number-input.md
> +| `step` | `number` | 1 | 每次递增/减的数值。 |
```suggestion
| `step` | `number` | 1 | 每次递增/递减的数值。 |
```

2021-09-21 15:48 UTC, Justineo commented on one/docs/components/transfer.md
> +设置 `merge-checked` 来指定选中值的多种模式。
```suggestion
设置 `merge-checked` 来指定选中值的合并模式。
```

2021-09-21 15:48 UTC, Justineo commented on one/docs/components/transfer.md
> +### 选中值的多种模式
```suggestion
### 选中值的合并模式
```

2021-09-21 15:48 UTC, Justineo commented on one/docs/demo/alert/extra.vue
> +<style lang="less" scoped docs>
把 `docs` 都去掉吧，我准备让 playground 里面和 demo 源码保持一致。

2021-09-21 15:48 UTC, Justineo commented on one/docs/demo/calendar/date-class.vue
> +.custom-date button {
不要用 element selector，demo 里面怎么写，业务代码里面都会抄过去的

2021-09-21 15:48 UTC, Justineo commented on one/docs/demo/calendar/fill-month.vue
> +  />
感觉可以搞一个 Switch 或者 Checkbox，会简单一点

2021-09-30 03:30 UTC, Justineo requested changes

2021-09-30 03:30 UTC, Justineo commented on one/docs/components/calendar.md
> +设置 `type` 来指定日历的类型：年，月，日。
```suggestion
设置 `type` 来指定日历的类型：年、月、日。
```

2021-09-30 03:30 UTC, Justineo commented on one/docs/components/check-button-group.md
> +在数据源的项目中设置 `desc` 字段或者通过 `desc`插槽 来指定额外描述，额外描述会在悬浮时显示。
```suggestion
在数据源的项目中设置 `desc` 字段或者通过 `desc` 插槽来指定额外描述。额外描述会在悬浮时显示。
```

2021-09-30 03:30 UTC, Justineo commented on one/docs/components/check-button-group.md
> +通过自定义CSS属性 `--dls-checkbox-button-stable: initial;` 来开启项目的最小宽度。
这个删了吧，加到 `ui` 里面。

2021-09-30 03:30 UTC, Justineo commented on one/docs/components/check-button-group.md
> +复选按钮组数据源，项目类型为 `{label, value, disabled, exclusive, desc ...}`。
```suggestion
复选按钮组数据源，项目类型为 `{ label, value, disabled, exclusive, desc, ... }`。
```

2021-09-30 03:30 UTC, Justineo commented on one/docs/components/check-button-group.md
> +| `desc` | 按钮的额外描述信息，作用域参数就是该数据项， |
```suggestion
| `desc` | 按钮的额外描述信息，作用域参数同 `item` 插槽。 |
```

2021-09-30 03:30 UTC, Justineo commented on one/docs/components/checkbox-group.md
> +在数据源的项目中设置 `desc` 字段或者通过 `desc`插槽 来指定额外描述，额外描述会在悬浮时显示。
```suggestion
在数据源的项目中设置 `desc` 字段或者通过 `desc` 插槽来指定额外描述。额外描述会在悬浮时显示。
```

2021-09-30 03:30 UTC, Justineo commented on one/docs/components/checkbox-group.md
> +复选框组数据源，项目类型为 `{label, value, disabled, exclusive, desc ...}`。
```suggestion
复选框组数据源，项目类型为 `{ label, value, disabled, exclusive, desc, ... }`。
```

2021-09-30 03:30 UTC, Justineo commented on one/docs/components/checkbox-group.md
> +| `desc` | 按钮的额外描述信息，作用域参数就是该数据项， |
```suggestion
| `desc` | 按钮的额外描述信息，作用域参数同 `item` 插槽。 |
```

2021-09-30 03:30 UTC, Justineo commented on one/docs/components/radio-button-group.md
> +在数据源的项目中设置 `desc` 字段或者通过 `desc`插槽 来指定额外描述，额外描述会在悬浮时显示。
```suggestion
在数据源的项目中设置 `desc` 字段或者通过 `desc` 插槽来指定额外描述。额外描述会在悬浮时显示。
```

2021-09-30 03:30 UTC, Justineo commented on one/docs/components/radio-button-group.md
> +通过自定义CSS属性 `--dls-radio-button-stable: initial;` 来开启项目的最小宽度。
`ui`

2021-09-30 03:30 UTC, Justineo commented on one/docs/components/radio-button-group.md
> +单选按钮组数据源，项目类型为 `{label, value, disabled, desc ...}`。
```suggestion
单选按钮组数据源，项目类型为 `{ label, value, disabled, desc, ... }`。
```

2021-09-30 03:30 UTC, Justineo commented on one/docs/components/radio-button-group.md
> +| `desc` | 按钮的额外描述信息，作用域参数就是该数据项， |
```suggestion
| `desc` | 按钮的额外描述信息，作用域参数同 `item` 插槽。 |
```

2021-09-30 03:30 UTC, Justineo commented on one/docs/components/radio-group.md
> +在数据源的项目中设置 `desc` 字段或者通过 `desc`插槽 来指定额外描述，额外描述会在悬浮时显示。
```suggestion
在数据源的项目中设置 `desc` 字段或者通过 `desc` 插槽来指定额外描述。额外描述会在悬浮时显示。
```

2021-09-30 03:30 UTC, Justineo commented on one/docs/components/radio-group.md
> +单选框组数据源，项目类型为 `{label, value, disabled, desc ...}`。
```suggestion
单选框组数据源，项目类型为 `{ label, value, disabled, desc, ... }`。
```

2021-09-30 03:30 UTC, Justineo commented on one/docs/components/radio-group.md
> +| `desc` | 按钮的额外描述信息，作用域参数就是该数据项， |
```suggestion
| `desc` | 按钮的额外描述信息，作用域参数同 `item` 插槽。 |
```

2021-09-30 03:30 UTC, Justineo commented on one/docs/components/radio-group.md
> +| `desc` | 按钮的额外描述信息，作用域参数就是该数据项， |
`item` 插槽 `desc` 字段漏了，其他地方也要看一下。

2021-09-30 03:30 UTC, Justineo commented on one/docs/components/uploader.md
> +### 继续上传的操作选项
这个是“上传入口自定义操作”？

2021-09-30 03:30 UTC, Justineo commented on one/docs/components/uploader.md
> +### 上传项的操作选项
“已上传项自定义操作作”？

2021-09-30 03:30 UTC, Justineo commented on one/docs/components/uploader.md
> +控制继续上传项目悬浮时的操作项，如继续添加等，会传递默认的操作项数组作为参数，返回实际生效的操作项数组。操作项对象参考 `controls` 属性的字段详情。
```suggestion
控制上传入口自定义操作，如从外部选择等。会传递默认的操作项数组作为参数，返回实际生效的操作项数组。操作项对象参考 `controls` 属性的字段详情。
```

2021-09-30 03:30 UTC, Justineo commented on one/docs/demo/carousel/ratio.vue
> +    <h4>按`2/1`比例展示轮播项</h4>
```suggestion
    <h4>按 `2/1` 比例展示轮播项</h4>
```

2021-10-13 04:24 UTC, Justineo requested changes

2021-10-13 04:24 UTC, Justineo commented on one/docs/components/nav.md
> +^^^
```suggestion
^^^active
当前激活节点，若该节点定义了 `name` 则就是该 `name` 值，否则该值是由 `to` 生成的路由路径（[route.path](https://router.vuejs.org/zh/api/#%E8%B7%AF%E7%94%B1%E5%AF%B9%E8%B1%A1%E5%B1%9E%E6%80%A7)）。
^^^
```

2021-10-13 04:24 UTC, Justineo commented on one/docs/components/nav.md
> +| `to` | `string|Object` | 节点的导航目的地。参考 [`Link`](./link) 组件的 [`to`](./link#props) 属性。 |
```suggestion
| `to` | `string | Object` | 节点的导航目的地。参考 [`Link`](./link) 组件的 [`to`](./link#props) 属性。 |
```

2021-10-13 04:24 UTC, Justineo commented on one/docs/components/nav.md
> +| `to` | `string|Object` | 节点的导航目的地。参考 [`Link`](./link) 组件的 [`to`](./link#props) 属性。 |
```suggestion
| `to` | `string | Object` | 节点的导航目的地。参考 [`Link`](./link) 组件的 [`to`](./link#props) 属性。 |
```

2021-10-13 04:24 UTC, Justineo commented on one/docs/demo/calendar/date-class.vue
> +      :fill-month="false"
这里就不用展示这个了吧

```suggestion
```

2021-10-13 04:24 UTC, Justineo commented on one/docs/demo/calendar/disabled-date.vue
> +    <h4>今日之前不可选</h4>
```suggestion
    <h4>只允许选未来的日期</h4>
```

2021-10-13 04:24 UTC, Justineo commented on one/docs/demo/check-button-group/desc.vue
> +      desc="a description for coffee."
这是干啥的

2021-10-13 04:24 UTC, Justineo commented on one/docs/demo/checkbox-group/desc.vue
> +      ui="simple"
```suggestion
```

2021-10-13 04:24 UTC, Justineo commented on one/docs/demo/checkbox-group/desc.vue
> +      ui="simple"
```suggestion
```

2021-10-13 04:24 UTC, Justineo commented on one/docs/demo/checkbox-group/desc.vue
> +      desc="a description for coffee."
```suggestion
```

2021-10-13 04:24 UTC, Justineo commented on one/docs/demo/check-button-group/desc.vue
> +      <template slot="desc">A description for coffee.</template>
用 scoped slots，而且不要写 `slot`/`slot-scope` 了，用 `#desc="{ desc }"` 吧， 展示实际场景下的用法。

2021-10-13 04:24 UTC, Justineo commented on one/docs/demo/radio-button-group/desc.vue
> +      <template slot="desc">A description for coffee.</template>
同上

2021-10-13 04:24 UTC, Justineo commented on one/docs/demo/radio-group/desc.vue
> +      <template slot="desc">A description for coffee.</template>
同上

2021-10-13 04:24 UTC, Justineo commented on one/docs/demo/uploader/entries.vue
> +        // debugger
```suggestion
```

2021-10-13 04:24 UTC, Justineo commented on one/docs/demo/uploader/entries.vue
> +      toast.info('You click star!')
```suggestion
      toast.info('You clicked star!')
```

2021-10-25 05:44 UTC, Justineo commented on one/docs/components/search-box.md
> +| `match` | `(item, keyword, { ancestors }) => boolean | Array<[number, number]>` | - | 支持自定义高亮逻辑， 默认大小写不敏感，参考 [`Autocomplete`](./Autocomplete#自定义搜索逻辑)。 |
```suggestion
| `match` | `(item, keyword, { ancestors }) => boolean | Array<[number, number]>` | - | 支持自定义高亮逻辑，默认大小写不敏感。参考 [`Autocomplete`](./Autocomplete#自定义搜索逻辑)。 |
```

2021-10-25 05:44 UTC, Justineo commented on one/docs/components/select.md
> +| `match` | `(item, keyword, { ancestors }) => boolean | Array<[number, number]>` | - | 支持自定义高亮逻辑， 默认大小写不敏感，参考 [`Autocomplete`](./Autocomplete#自定义搜索逻辑)。 |
```suggestion
| `match` | `(item, keyword, { ancestors }) => boolean | Array<[number, number]>` | - | 支持自定义高亮逻辑，默认大小写不敏感。参考 [`Autocomplete`](./Autocomplete#自定义搜索逻辑)。 |
```

2021-10-25 05:44 UTC, Justineo commented on one/docs/components/cascader.md
> +| `match` | `(item, keyword, { ancestors }) => boolean | Array<[number, number]>` | - | 支持自定义高亮逻辑， 默认大小写不敏感，参考 [`Autocomplete`](./Autocomplete#自定义搜索逻辑)。 |
```suggestion
| `match` | `(item, keyword, { ancestors }) => boolean | Array<[number, number]>` | - | 支持自定义高亮逻辑，默认大小写不敏感。参考 [`Autocomplete`](./Autocomplete#自定义搜索逻辑)。 |
```

2021-10-25 05:44 UTC, Justineo commented on one/docs/components/dropdown.md
> +| `match` | `(item, keyword, { ancestors }) => boolean | Array<[number, number]>` | - | 支持自定义高亮逻辑， 默认大小写不敏感，参考 [`Autocomplete`](./Autocomplete#自定义搜索逻辑)。 |
```suggestion
| `match` | `(item, keyword, { ancestors }) => boolean | Array<[number, number]>` | - | 支持自定义高亮逻辑，默认大小写不敏感。参考 [`Autocomplete`](./Autocomplete#自定义搜索逻辑)。 |
```

2021-10-25 05:44 UTC, Justineo commented on one/docs/components/dropdown.md
> +| `filter` | `(item, keyword, { ancestors, offsets }) => boolean` | - | 支持自定义搜索命中逻辑，参考 [`Autocomplete`](./Autocomplete#自定义搜索逻辑)。 |
```suggestion
| `filter` | `(item, keyword, { ancestors, offsets }) => boolean` | - | 支持自定义搜索命中逻辑。参考 [`Autocomplete`](./Autocomplete#自定义搜索逻辑)。 |
```

2021-10-25 05:44 UTC, Justineo commented on one/docs/components/search-box.md
> +| `filter` | `(item, keyword, { ancestors, offsets }) => boolean` | - | 支持自定义搜索命中逻辑，参考 [`Autocomplete`](./Autocomplete#自定义搜索逻辑)。 |
```suggestion
| `filter` | `(item, keyword, { ancestors, offsets }) => boolean` | - | 支持自定义搜索命中逻辑。参考 [`Autocomplete`](./Autocomplete#自定义搜索逻辑)。 |
```

2021-10-25 05:44 UTC, Justineo commented on one/docs/components/select.md
> +| `filter` | `(item, keyword, { ancestors, offsets }) => boolean` | - | 支持自定义搜索命中逻辑，参考 [`Autocomplete`](./Autocomplete#自定义搜索逻辑)。 |
```suggestion
| `filter` | `(item, keyword, { ancestors, offsets }) => boolean` | - | 支持自定义搜索命中逻辑。参考 [`Autocomplete`](./Autocomplete#自定义搜索逻辑)。 |
```

2021-10-25 05:44 UTC, Justineo commented on one/docs/components/cascader.md
> +| `filter` | `(item, keyword, { ancestors, offsets }) => boolean` | - | 支持自定义搜索命中逻辑，参考 [`Autocomplete`](./Autocomplete#自定义搜索逻辑)。 |
```suggestion
| `filter` | `(item, keyword, { ancestors, offsets }) => boolean` | - | 支持自定义搜索命中逻辑。参考 [`Autocomplete`](./Autocomplete#自定义搜索逻辑)。 |
```

2021-10-25 10:41 UTC, Justineo requested changes

2021-10-25 10:41 UTC, Justineo commented on one/docs/components/check-button-group.md
> +| ``desc`` | 按钮的额外描述信息，作用域参数同 `item` 插槽。 |
```suggestion
| ``desc`` | 按钮的额外描述信息，作用域参数同 [`item`](#slots-item) 插槽。 |
```

2021-10-25 10:41 UTC, Justineo commented on one/docs/components/checkbox-group.md
> +| ``desc`` | 按钮的额外描述信息，作用域参数同 `item` 插槽。 |
```suggestion
| ``desc`` | 按钮的额外描述信息，作用域参数同 [`item`](#slots-item) 插槽。 |
```

2021-10-25 10:41 UTC, Justineo commented on one/docs/components/anchor.md
> +[`target-offset`](#props-target-offset) 用来控制锚点滚动到容器何处开始处于激活状态。
```suggestion
用 [`target-offset`](#props-target-offset) 属性来控制锚点滚动到容器何处开始处于激活状态。
```

2021-10-25 10:41 UTC, Justineo commented on one/docs/components/anchor.md
> +[`sticky-offset`](#props-sticky-offset) 用来控制 `Anchor` 处于容器何处时开始吸附。
```suggestion
用 [`sticky-offset`](#props-sticky-offset) 属性来控制 `Anchor` 处于容器何处时开始吸附。
```

2021-10-25 10:41 UTC, Justineo commented on one/docs/components/nav.md
> +默认内容：渲染了 `icon` 插槽和 `item-label` 插槽。
好像没有写 `icon` 插槽？

2021-10-25 10:41 UTC, Justineo commented on one/docs/components/nav.md
> +| `children` | `Array<Object>=` | 节点的子节点数组，数组项类型同 `items` 数组项。 |
```suggestion
| `children` | `Array<Object>=` | 节点的子节点数组，数组项类型同 [`items`](#props-items) 属性数组项。 |
```

2021-10-25 10:41 UTC, Justineo commented on one/docs/components/nav.md
> +作用域参数参考 `item` 插槽。
```suggestion
作用域参数参考 [`item`](#slots-item) 插槽。
```

2021-10-25 10:41 UTC, Justineo commented on one/docs/components/nav.md
> +| `activate` | 用户点击有 `to` 的节点触发，参数是激活节点的整个 `item` 数据。 |
```suggestion
| `activate` | 用户点击有 `to` 的节点触发，参数是激活节点在 [`items`](#props-items) 属性中对应的数据项。 |
```

2021-10-25 10:41 UTC, Justineo commented on one/docs/components/nav.md
> +| `click` | 用户点击节点时触发，参数是激活节点整个 `item` 数据。 |
```suggestion
| `click` | 用户点击节点时触发，参数是激活节点在 [`items`](#props-items) 属性中对应的数据项。 |
```

2021-10-25 10:41 UTC, Justineo commented on one/docs/components/nav.md
> +| `ui` | `string=` | - | [^ui] |
需要页内跳转的要用 <code>\`\`ui\`\`</code>，下同

2021-10-25 10:41 UTC, Justineo commented on one/docs/components/radio-button-group.md
> +设置 `ui` 属性值：`simple` 来指定简单样式。
```suggestion
设置 [`ui`](#props-ui) 属性值：`simple` 来指定简单样式。
```

2021-10-25 10:41 UTC, Justineo commented on one/docs/components/radio-button-group.md
> +| ``desc`` | 按钮的额外描述信息，作用域参数同 `item` 插槽。 |
```suggestion
| ``desc`` | 按钮的额外描述信息，作用域参数同 [`item`](#slots-item) 插槽。 |
```

2021-10-25 10:41 UTC, Justineo commented on one/docs/components/radio-group.md
> +| ``desc`` | 按钮的额外描述信息，作用域参数同 `item` 插槽。 |
```suggestion
| ``desc`` | 按钮的额外描述信息，作用域参数同 [`item`](#slots-item) 插槽。 |
```

2021-10-25 10:41 UTC, Justineo commented on one/docs/components/select.md
> +使用 `label` 插槽来自定义**下拉关闭时**已选项如何展示。
```suggestion
使用 [`label`](#slots-label) 插槽来自定义**下拉关闭时**已选项如何展示。
```

2021-10-25 10:41 UTC, Justineo commented on one/docs/components/select.md
> +使用 `select` 插槽来自定义已选项如何展示，和下拉是否关闭无关。
```suggestion
使用 [`selected`](#slots-selected) 插槽来自定义已选项如何展示，和下拉是否关闭无关。
```

2021-10-25 10:41 UTC, Justineo commented on one/docs/components/steps.md
> +可以通过设置 [`steps`](#props-steps) 的 `status` 属性值定义步骤状态，若步骤出错，可设置为 `error`。
```suggestion
可以通过设置 [`steps`](#props-steps) 属性数据项的 `status` 自动值定义步骤状态，若步骤出错，可设置为 `error`。
```

2021-10-25 10:41 UTC, Justineo commented on one/docs/components/table.md
> +使用 `order` 属性和 `order-by` 属性来指定表头上的排序状态。
```suggestion
使用 [`order`](#props-order) 属性和 [`order-by`](#props-order-by) 属性来指定表头上的排序状态。
```

2021-10-25 10:41 UTC, Justineo commented on one/docs/components/table.md
> +监听 `sort` 事件来处理排序状态的变化。
```suggestion
监听 [`sort`](#events-sort) 事件来处理排序状态的变化。
```

2021-10-25 10:41 UTC, Justineo commented on one/docs/components/table.md
> +设置 `allowed-orders` 属性来自定义允许的排序状态。
```suggestion
设置 [`allowed-orders`](#props-allowed-orders) 属性来自定义允许的排序状态。
```

2021-10-25 10:41 UTC, Justineo commented on one/docs/components/table.md
> +使用 `loading` 属性来指定表格处于加载状态。
```suggestion
使用 [`loading`](#props-loading) 属性来指定表格处于加载状态。
```

2021-10-25 11:16 UTC, xiaodemen commented on one/docs/components/nav.md
> +默认内容：渲染了 `icon` 插槽和 `item-label` 插槽。
目前 icon 的实现比较怪，先不暴露了？

2021-10-25 11:34 UTC, Justineo commented on one/docs/components/nav.md
> +| `click` | 用户点击节点时触发，参数是激活节点在 [`items`](#props-items) 属性中对应的数据项。 |
事件、图标、配置也是 public API，也加上 anchor 吧。

2021-10-25 12:10 UTC, merged