feat: add column desc api and example
ecomfe/veui-docs pull request #2
Opened 2020-11-30 04:01 UTC by Phinome

2020-11-30 04:09 UTC, Justineo requested changes

2020-11-30 04:09 UTC, Justineo commented on one/docs/components/table.md
> +| `desc` | `string` | - | 表头节点的注释。 |
这个是 Column 的 prop 吧……

2020-11-30 04:09 UTC, Justineo commented on one/docs/components/table.md
> +| `desc` | [^scoped-slot-desc] |
同上

2020-11-30 04:09 UTC, Justineo commented on one/docs/components/table.md
> +^^^
同上。另外不要提 Popover，这只是一个实现细节，描述功能就可以了。

2020-11-30 04:09 UTC, Justineo commented on one/docs/components/table.md
> +### 表头注释
是表头描述吧

2020-11-30 04:09 UTC, Justineo commented on one/docs/demo/table/desc.vue
> +</style>
实例内容用英文，可以把不太必要的内容都删掉，比如可以切换的 `ui`、删除行等等。

2020-11-30 15:56 UTC, Justineo requested changes

2020-11-30 15:56 UTC, Justineo commented on one/docs/demo/table/desc.vue
> +      size: 'm',
```suggestion
```

2020-11-30 15:56 UTC, Justineo commented on one/docs/demo/table/desc.vue
> +    }
```suggestion
```

2020-11-30 15:56 UTC, Justineo commented on one/docs/demo/table/desc.vue
> +      nameDesc: "This is a description for name."
```suggestion
      nameDesc: ‘This is a description for name.’
```

2020-11-30 15:56 UTC, Justineo commented on one/docs/demo/table/desc.vue
> +      </veui-table-column>
这些复杂的东西都不需要了，其它的 demo 里面演示过了。

2020-12-01 02:18 UTC, Justineo commented
Ps. 不要提交 `package-lock.json`。

2020-12-01 02:21 UTC, Phinome commented
意思是忽略 `package-lock.json` ？

2020-12-01 02:27 UTC, Justineo commented
你不要提交 `package-lock.json` 就可以了，需要更新的时候我统一改就行了。你从 taobao 源装的，会导致很多不必要的改变。

2020-12-01 02:30 UTC, Phinome commented
原来如此，好的~

2020-12-01 02:53 UTC, Justineo commented on one/docs/components/table.md
> +支持表头增加描述
```suggestion
使用 `desc` 属性或 `desc` 插槽来为表头增加描述信息。
```

2020-12-01 02:54 UTC, merged